In [1]:
import numpy as np
a=np.ones([4,2],dtype=np.uint16)
print(a)
print(a.shape)
print(a.ndim)
print(a.itemsize)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]
(4, 2)
2
2


In [2]:
import numpy as np
np.arange(100,200,10).reshape(5,2)

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [3]:
import numpy as np
b= np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
b[0:,2]

array([33, 66, 99])

In [4]:
import numpy as np
c = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(c)
c[0::2,1::2]

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]


array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [5]:
import numpy as np
a1 = np.array([[5, 6, 9], [21 ,18, 27]])
a2 = np.array([[15 ,33, 24], [4 ,7, 1]]) 
d=a1+a2
d
np.sqrt(d)

array([[4.47213595, 6.244998  , 5.74456265],
       [5.        , 5.        , 5.29150262]])

In [6]:
e=d*d
e

array([[ 400, 1521, 1089],
       [ 625,  625,  784]])

In [7]:
import numpy as np
f = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(f)
print(f[:,f[1,:].argsort()])
print(f[f[:,1].argsort()])

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[73 43 34]
 [12 22 82]
 [66 94 53]]
[[82 22 12]
 [34 43 73]
 [53 94 66]]


In [8]:
import pandas as pd
df = pd.read_csv('Automobile_data.csv')
df[df['price']==df['price'].max()][['company']]

company
35  mercedes-benz

In [9]:
import pandas as pd
df = pd.read_csv('Automobile_data.csv')
df.groupby('company')['price'].max()

company
alfa-romero      16500.0
audi             18920.0
bmw              41315.0
chevrolet         6575.0
dodge             6377.0
honda            12945.0
isuzu             6785.0
jaguar           36000.0
mazda            18344.0
mercedes-benz    45400.0
mitsubishi        8189.0
nissan           13499.0
porsche          37028.0
toyota           15750.0
volkswagen        9995.0
volvo            13415.0
Name: price, dtype: float64

In [10]:
import pandas as pd
df = pd.read_csv('Automobile_data.csv')
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
df1 = pd.DataFrame.from_dict(GermanCars)
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}
df2 = pd.DataFrame.from_dict(japaneseCars)
x = pd.concat([df1,df2], keys=["Germany", "Japan"])
x

Company   Price
Germany 0         Ford   23845
        1     Mercedes  171995
        2          BMV  135925
        3         Audi   71400
Japan   0       Toyota   29995
        1        Honda   23600
        2       Nissan   61500
        3  Mitsubishi    58900

In [11]:
import pandas as pd
df = pd.read_csv('Automobile_data.csv')
z=df.sort_values(by=['price'])
z

index        company body-style  wheel-base  length engine-type  \
13     16      chevrolet  hatchback        88.4   141.1           l   
27     36          mazda  hatchback        93.1   159.1         ohc   
48     66         toyota  hatchback        95.7   158.7         ohc   
36     49     mitsubishi  hatchback        93.7   157.3         ohc   
28     37          mazda  hatchback        93.1   159.1         ohc   
..    ...            ...        ...         ...     ...         ...   
11     14            bmw      sedan       103.5   193.8         ohc   
35     47  mercedes-benz    hardtop       112.0   199.2        ohcv   
22     31          isuzu      sedan        94.5   155.9         ohc   
23     32          isuzu      sedan        94.5   155.9         ohc   
47     63        porsche  hatchback        98.4   175.7       dohcv   

   num-of-cylinders  horsepower  average-mileage    price  
13            three          48               47   5151.0  
27             four          68               30   5195.0  
48             four          62               35   5348.0  
36             four          68               37   5389.0  
28             four          68               31   6095.0  
..              ...         ...              ...      ...  
11              six         182               16  41315.0  
35            eight         184               14  45400.0  
22             four          70               38      NaN  
23             four          70               38      NaN  
47            eight         288               17      NaN  

[61 rows x 10 columns]

In [12]:
import pandas as pd
df = pd.read_csv('Automobile_data.csv')
df['company'].value_counts()

toyota           7
bmw              6
mazda            5
nissan           5
mercedes-benz    4
audi             4
volkswagen       4
mitsubishi       4
isuzu            3
chevrolet        3
jaguar           3
honda            3
alfa-romero      3
porsche          3
volvo            2
dodge            2
Name: company, dtype: int64